//
// Created by maxon on 26.05.18.
//

#ifndef UNIVERSALSTORAGE_MAPPEDFILEBLOCKMANAGER_H
#define UNIVERSALSTORAGE_MAPPEDFILEBLOCKMANAGER_H


class MappedFileBlockManager
{

};


#endif //UNIVERSALSTORAGE_MAPPEDFILEBLOCKMANAGER_H
